# Generated by Django 3.2.5 on 2021-07-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('sender_name', models.CharField(max_length=50, verbose_name='Имя отправителя')),
                ('sender_addres', models.TextField(verbose_name='Адрес отправителя')),
                ('receiver', models.CharField(max_length=50, verbose_name='Имя получателя')),
                ('receiver_address', models.TextField(verbose_name='Адрес получателя')),
                ('date_of_creating', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('weigth', models.IntegerField(verbose_name='Вес посылки, г.')),
            ],
        ),
    ]
